import type { ColumnType } from "kysely";

// Type for timestamps that are generated by the database
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

// Type for timestamps
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

// User table interface
export interface UsersTable {
	id: Generated<number>;
	name: string;
	email: string;
	age: number;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

// Database interface - add your tables here
export interface Database {
	users: UsersTable;
}
