export { checkDatabaseConnection, closeDatabaseConnection, db } from "./database";
export type {
	AdoptionRequestsTable,
	AdoptionStatusesTable,
	AssignmentsTable,
	Database,
	EventsTable,
	PetColorsTable,
	PetPetColorsTable,
	PetPhotosTable,
	PetSizesTable,
	PetSpeciesTable,
	PetStatusesTable,
	PetsTable,
	RolesTable,
	SexesTable,
	SheltersTable,
	UsersTable,
	VaccinationsTable,
	VaccinesTable,
} from "./database.types";
